services:
  dev_flyway:
    image: flyway/flyway:12.1.0-alpine-mongo
    container_name: local_flyway
    restart: "no"
    env_file:
      - ../env/.env.local
    environment:
      FLYWAY_SCHEMAS: ops_flyway
    networks:
      - local_net
    volumes:
      - ../../migrations:/flyway/sql

networks:
  dev_net:
    driver: bridge