DROP TRIGGER IF EXISTS registry_t_users_trg_log_access_level_changed_to_manager
ON registry.t_users;

CREATE TRIGGER registry_t_users_trg_log_access_level_changed_to_manager
AFTER UPDATE ON registry.t_users
FOR EACH ROW
EXECUTE FUNCTION logs.fn_log_user_access_level_changed_to_manager();
