DROP TRIGGER IF EXISTS registry_t_companies_clientes_trg_is_valid_created_at
ON registry.t_companies_clients;

CREATE TRIGGER registry_t_companies_clientes_trg_is_valid_created_at
BEFORE INSERT OR UPDATE ON registry.t_companies_clients
FOR EACH ROW
EXECUTE FUNCTION functions.fn_is_valid_created_at();
