DROP TRIGGER IF EXISTS registry_t_company_clients_trg_log_created
ON registry.t_companies_clients;

CREATE TRIGGER registry_t_company_clients_trg_log_created
AFTER INSERT ON registry.t_companies_clients
FOR EACH ROW
EXECUTE FUNCTION logs.fn_log_company_client_created();