DROP TRIGGER IF EXISTS registry_t_contracts_types_trg_log_contract_type_created
ON registry.t_contracts_types;

CREATE TRIGGER registry_t_contracts_types_trg_log_contract_type_created
AFTER INSERT ON registry.t_contracts_types
FOR EACH ROW
EXECUTE FUNCTION logs.fn_log_contract_type_created();