DROP TRIGGER IF EXISTS registry_t_companies_clients_trg_update_updated_at
ON registry.t_companies_clients;

CREATE TRIGGER registry_t_companies_clients_trg_update_updated_at
BEFORE UPDATE ON registry.t_companies_clients
FOR EACH ROW
EXECUTE FUNCTION functions.fn_update_updated_at();